// lib/userdata.mjs — UNA política para tocar archivos que pueden tener trabajo del usuario.
// Responsabilidad ÚNICA: que chalc no pierda nada al reescribir.
//
// Antes cada sitio decidía a su manera (mergeJson respaldaba, gate.json descartaba en silencio,
// la config global se reemplazaba por `{}`, las specs se reescribían con sus casillas marcadas). La
// regla ahora depende de quién es dueño del archivo:
//   1. Lo que chalc escribe y puede llevar trabajo del usuario (config, .chalc.json, gate.json,
//      .mcp.json, locks y entradas de QA, specs): lo ILEGIBLE se copia a `<archivo>.invalid-<marca>`,
//      se avisa y se sigue con el valor por defecto; lo que se va a REEMPLAZAR con contenido distinto
//      se copia antes a `.chalc/backups/` y se avisa. Nunca se descarta en silencio.
//   2. Lo del catálogo del paquete (reglas, roles, tabla de herramientas): ilegible se avisa con su
//      archivo y se omite (y `doctor` lo da como error).
//   3. Lo de terceros que chalc solo LEE para detectar (el package.json del proyecto…): ilegible es
//      como ausente; chalc nunca lo escribe, así que no hay nada que proteger.
//   4. Líneas de registros y flujos (JSONL, salida de un servidor MCP, respuestas del modelo): se
//      salta la línea mala y se sigue con las demás.
// Los secretos, además, se escriben con `writeSecureFileSync` (atómico y solo para el dueño).

import { copyFileSync, existsSync, readFileSync } from 'node:fs';
import { cp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { basename, dirname, isAbsolute, join, relative } from 'node:path';

const stamp = () => new Date().toISOString().replace(/[:.]/g, '-');

// Los avisos salen en el idioma de la interfaz. i18n.mjs depende de este módulo (lee la config al
// arrancar), así que no se puede importar aquí: es él quien registra sus textos al terminar de
// cargar. Hasta entonces —solo durante ese arranque— se avisa en inglés.
// `reason` dice por qué se respalda: 'replaced' (contenido distinto), 'notOursSkill' (una carpeta de
// skill que chalc no generó), 'notOursRule' (una regla sin la marca de chalc).
const REASONS_EN = { replaced: 'is being replaced', notOursSkill: 'was not generated by chalc and is replaced by the catalog one', notOursRule: 'does not carry the chalc mark and is removed' };
let notices = {
  invalid: (file, why, backup) => `${file} is not valid JSON (${why}); backup: ${backup}`,
  backedUp: (file, reason, backup) => `${file} ${REASONS_EN[reason] || reason}; previous copy at ${backup}`
};

/** Textos de los avisos en el idioma de la interfaz (los registra i18n.mjs). */
export function setUserdataNotices(next) { notices = { ...notices, ...next }; }

// Una copia y un aviso por archivo y proceso: un archivo roto que se lee en cada turno no puede
// llenar la carpeta de copias idénticas ni la consola de avisos repetidos.
const kept = new Set();
function keepInvalid(file, error) {
  if (kept.has(file)) return;
  kept.add(file);
  const backup = `${file}.invalid-${stamp()}`;
  try { copyFileSync(file, backup); } catch { return; }
  console.warn(`  ! ${notices.invalid(file, error?.message || error, backup)}`);
}

/** JSON de `file`, o `fallback` si no existe. Si existe pero no se puede leer, se respalda y se avisa. */
export function readJsonOrKeepSync(file, fallback = {}) {
  if (!existsSync(file)) return fallback;
  try { return JSON.parse(readFileSync(file, 'utf8')); } catch (e) { keepInvalid(file, e); return fallback; }
}

export async function readJsonOrKeep(file, fallback = {}) {
  if (!existsSync(file)) return fallback;
  try { return JSON.parse(await readFile(file, 'utf8')); } catch (e) { keepInvalid(file, e); return fallback; }
}

// Dónde queda la copia de `abs`: dentro de `<root>/.chalc/backups/`, con su ruta relativa al
// proyecto; si `abs` está fuera del proyecto, junto a él.
function backupTarget(root, abs) {
  const rel = relative(root, abs);
  const inside = rel && rel.split(/[\\/]/)[0] !== '..' && !isAbsolute(rel);
  return inside ? join(root, '.chalc', 'backups', `${rel}.${stamp()}`) : join(dirname(abs), `${basename(abs)}.${stamp()}.bak`);
}

/** Copia `abs` (archivo o carpeta) a la zona de respaldos y avisa. Devuelve la ruta de la copia. */
export async function backupBeforeReplace(root, abs, reason = 'replaced') {
  if (!existsSync(abs)) return null;
  const target = backupTarget(root, abs);
  await mkdir(dirname(target), { recursive: true });
  await cp(abs, target, { recursive: true, dereference: false });
  console.warn(`  ! ${notices.backedUp(relative(root, abs) || abs, reason, relative(root, target) || target)}`);
  return target;
}

/**
 * Escribe `content` en `file`. Si ya existía con OTRO contenido, primero lo respalda: regenerar una
 * spec reescribía `tasks.md` y se perdían las casillas marcadas, que son el progreso del equipo.
 */
export async function writeKeepingPrevious(root, file, content) {
  if (existsSync(file) && (await readFile(file, 'utf8')) !== content) await backupBeforeReplace(root, file);
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, content);
}
